BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_release: app.press_clear()

#    Button:
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Great'
        on_press: app.handle_greet()

    Label:
        id: output_label
        text: 'Enter your name'
        color: (1, 1, 0, 1)

     Button:
        text: 'Clear'
        on_release: app.press_clear()